#! /bin/sh
### BEGIN INIT INFO
# Provides:          php-fastcgi
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop php-cgi in external FASTCGI mode
# Description:       Start and stop php-cgi in external FASTCGI mode
### END INIT INFO

# Author: Kurt Zankl <kz@xon.uni.cc>

# Do NOT "set -e"

SCRIPTNAME=/etc/init.d/rw
SERVERINIT=/etc/init.d/nginx
ENGINEINIT=/etc/init.d/node

case "$1" in
  start)
        $SERVERINIT start
        $ENGINEINIT start
        ;;
  stop)
        $SERVERINIT stop
        $ENGINEINIT stop
        ;;
  status)
        $SERVERINIT status
        $ENGINEINIT status
        ;;
  restart|reload|force-reload)
        $SERVERINIT stop
        $ENGINEINIT stop
        $SERVERINIT start
        $ENGINEINIT start
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
        exit 3
        ;;
esac

