#!/bin/bash
#
# chkconfig: 35 90 12
# description: init script for a server
#
# Get function from functions library
. /etc/init.d/functions

initpath='/usr/local/bin'
initcommand='node'
initsuffix='/var/web-controllers/node_server.js'
outputlog='/var/log/node-output.log'

# Start the service
start() {
        echo -n "Starting "$initcommand" server: "
        if status $initcommand > /dev/null; then
            echo 
            status $initcommand
        else
            $initpath/$initcommand $initsuffix >> $outputlog &
            ### Create the lock file ###
            [ -d /var/lock/subsys ] || mkdir -p /var/lock/subsys
            touch /var/lock/subsys/$initcommand
            success $initcommand" server startup"
            echo
        fi
}
# Restart the service
stop() {
        echo -n "Stopping "$initcommand" server: "
        killproc $initcommand
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/$initcommand
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $initcommand
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0

